// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static   const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3Xt_Qv-0s8PFlHx7zlZYwAePqwyCH__Q',
    appId: '1:30362321268:android:b604de074877a7fd60ec21',
    messagingSenderId: '30362321268',
    projectId: 'ecowatt-a19da',
    storageBucket: 'ecowatt-a19da.appspot.com',
  );

  static  const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAY9iU8preAF_eULzMXKQI-h-x7maLEuTU',
    appId: '1:30362321268:ios:812e1fb21db73e7d60ec21',
    messagingSenderId: '30362321268',
    projectId: 'ecowatt-a19da',
    storageBucket: 'ecowatt-a19da.appspot.com',
    iosBundleId: 'com.example.ecowattYassineAskourFlutter',
  );
}
